#misc test runs
wip: -f pretty -t @wip
complete: -f pretty -t @complete -t ~@not_implemented
failing: -f pretty -t @complete -t @failing
complete_no_failing: -f pretty -t @complete -t ~@failing
specific: -f pretty --tags <%= ENV['TAGS'] %>
smoke: -f pretty --tags @smoke
feature: -f pretty -t @complete -t ~@failing  -t <%= ENV['TAGS'] %>
smoke_live: -f pretty --tags @smoke_live